{
    "id": "c2804e1e-bdf2-4491-a1a3-82ce9a7be43e",
    "object": "chat.completion",
    "created": 1744602323,
    "model": "deepseek-chat",
    "choices": [
        {
            "index": 0,
            "message": {
                "role": "assistant",
                "content": "",
                "tool_calls": [
                    {
                        "index": 0,
                        "id": "call_0_d59a5bb0-e2a3-4680-9d41-7f0047432510",
                        "type": "function",
                        "function": {
                            "name": "execute",
                            "arguments": "{\"function\":\"doc=FreeCAD.newDocument()\"}"
                        }
                    }
                ]
            },
            "logprobs": null,
            "finish_reason": "tool_calls"
        }
    ],
    "usage": {
        "prompt_tokens": 956,
        "completion_tokens": 23,
        "total_tokens": 979,
        "prompt_tokens_details": {
            "cached_tokens": 896
        },
        "prompt_cache_hit_tokens": 896,
        "prompt_cache_miss_tokens": 60
    },
    "system_fingerprint": "fp_3d5141a69a_prod0225"
}