{
    "id": "5e8d7c00-9f98-4c54-a3b9-c749e5e74d1f",
    "object": "chat.completion",
    "created": 1744447352,
    "model": "deepseek-chat",
    "choices": [
        {
            "index": 0,
            "message": {
                "role": "assistant",
                "content": "已执行 FreeCAD.newDocument() 命令，创建了一个新的 FreeCAD 文档。"
            },
            "logprobs": null,
            "finish_reason": "stop"
        }
    ],
    "usage": {
        "prompt_tokens": 32,
        "completion_tokens": 18,
        "total_tokens": 50,
        "prompt_tokens_details": {
            "cached_tokens": 0
        },
        "prompt_cache_hit_tokens": 0,
        "prompt_cache_miss_tokens": 32
    },
    "system_fingerprint": "fp_3d5141a69a_prod0225"
}